---
---
#Post-upgrade Job Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: post-install-rollout-role
rules:
- apiGroups: ["rollouts.kruise.io"]
  resources: ["rollouts"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: post-install-rollout-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: post-install-rollout-role